# Generated by Django 3.1.1 on 2020-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='photo',
            field=models.ImageField(upload_to='%d', verbose_name='사진'),
        ),
    ]
